---
- name: Installing Jenkins server
  hosts: all
  vars: 
    - executable_temp_dir: /tmp
    - kubectl_version: 1.25.5
    - kubectl_download_filetype: binary
    - kubectl_checksum_archive: sha512:c229b5700944f86f8312cb76d44248de813b8bae58026ec137b3e19bf422e91ed9848115bd549c5d5915b43acd639db71c2e9ece756c1b1c4f706672e11151b6
    - kubectl_bin_directory: /usr/local/bin
    - kubectl_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
    - kubectl_owner: root
    - kubectl_group: root
    - kubectl_binary_mode: 0755
    - kubectl_os: linux
    - kubectl_arch: amd64

  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Update all packages to their latest version
      apt:
        upgrade: yes
        update_cache: yes
      ignore_errors: true
    - name: Installing some packages
      apt:
        name: 
          - wget
          - git
          - curl
          - openjdk-11-jre
          - vim
          - pip
          - unzip
        state: latest
      ignore_errors: true

    - name: checking repository
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee \
        /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update all packages to their latest version
      apt:
        update_cache: yes
      ignore_errors: true

    - name: Installing Jenkins
      apt:
        name: jenkins
        state: latest

    - name: Make sure a service unit is running
      systemd:
        name: jenkins
        state: started
     # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    - name: Download awscliv2 installer.
      unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "{{ executable_temp_dir }}"
        remote_src: true
        creates: '{{ executable_temp_dir }}/aws'
        mode: 0755

    - name: Run the installer.
      command:
      args:
        cmd: "{{ executable_temp_dir }}/aws/install"
        creates: /usr/local/bin/aws
      become: true
      register: aws_install

    - name: "Show installer output."
      debug:
        var: aws_install
        verbosity: 2
    - name: remove any installed docker
      apt:
        name:
          - docker 
          - docker-engine 
          - docker.io 
          - containerd 
          - runc 
        state: absent
    - name: add docker-ce apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: docker-ce-stable deb repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
    - name: add docker group
      group:
        name: docker
        state: present
    - name: add $USER to docker group
      user: 
        name: ubuntu
        groups: docker
        append: yes
    - name: add jenkins to docker group
      user: 
        name: jenkins
        groups: docker
        append: yes
    - name: chmod 666 for /var/run/dovker.sock
      file:
       path: /var/run/docker.sock
       mode: '666'
    - name: Download kubectl archive
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/kubernetes-client-{{ kubectl_os }}-{{ kubectl_arch }}.tar.gz"
        checksum: "{{ kubectl_checksum_archive }}"
        dest: "{{ kubectl_tmp_directory }}"
        mode: 0600
      tags:
        - kubectl

    - name: Unarchive kubernetes-client
      ansible.builtin.unarchive:
        src: "{{ kubectl_tmp_directory }}/kubernetes-client-{{ kubectl_os }}-{{ kubectl_arch }}.tar.gz"
        dest: "{{ kubectl_tmp_directory }}"
        remote_src: true
      tags:
        - kubectl

    - name: Copy kubectl binary to destination directory
      ansible.builtin.copy:
        src: "{{ kubectl_tmp_directory }}/kubernetes/client/bin/{{ item }}"
        dest: "{{ kubectl_bin_directory }}/{{ item }}"
        mode: "{{ kubectl_binary_mode }}"
        owner: "{{ kubectl_owner }}"
        group: "{{ kubectl_group }}"
        remote_src: true
      with_items:
        - kubectl
                            
        
